[package]
name = "straterust-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[[bin]]
name = "straterust-headless"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
ron.workspace = true
straterust-engine.workspace = true

[lints]
workspace = true
