//! Original recording names grouped by unit and cue. These are archive data paths.
use straterust_engine::media::AudioCue;

pub fn paths(unit: usize, cue: AudioCue) -> Vec<String> {
    let names: &[&str] = match (unit, cue) {
        (2 | 16, AudioCue::Complete) => &["Gamesfx\\peasant\\pswrkdon.wav"],
        (3 | 17, AudioCue::Complete) => &["Gamesfx\\orc\\owrkdone.wav"],
        (0, AudioCue::Select) => &[
            "Gamesfx\\human\\hwhat1.wav",
            "Gamesfx\\human\\hwhat2.wav",
            "Gamesfx\\human\\hwhat3.wav",
            "Gamesfx\\human\\hwhat4.wav",
            "Gamesfx\\human\\hwhat5.wav",
            "Gamesfx\\human\\hwhat6.wav",
        ],
        (0, AudioCue::Order) => &[
            "Gamesfx\\human\\hyessir1.wav",
            "Gamesfx\\human\\hyessir2.wav",
            "Gamesfx\\human\\hyessir3.wav",
            "Gamesfx\\human\\hyessir4.wav",
        ],
        (0, AudioCue::Ready) => &["Gamesfx\\human\\hready.wav"],
        (1 | 3 | 17, AudioCue::Select) => &[
            "Gamesfx\\orc\\owhat1.wav",
            "Gamesfx\\orc\\owhat2.wav",
            "Gamesfx\\orc\\owhat3.wav",
            "Gamesfx\\orc\\owhat4.wav",
            "Gamesfx\\orc\\owhat5.wav",
            "Gamesfx\\orc\\owhat6.wav",
        ],
        (1 | 3 | 17, AudioCue::Order) => &[
            "Gamesfx\\orc\\oyessir1.wav",
            "Gamesfx\\orc\\oyessir2.wav",
            "Gamesfx\\orc\\oyessir3.wav",
            "Gamesfx\\orc\\oyessir4.wav",
        ],
        (1 | 3 | 17, AudioCue::Ready) => &["Gamesfx\\orc\\oready.wav"],
        (2 | 16, AudioCue::Select) => &[
            "Gamesfx\\peasant\\pswhat1.wav",
            "Gamesfx\\peasant\\pswhat2.wav",
            "Gamesfx\\peasant\\pswhat3.wav",
            "Gamesfx\\peasant\\pswhat4.wav",
        ],
        (2 | 16, AudioCue::Order) => &[
            "Gamesfx\\peasant\\psyessr1.wav",
            "Gamesfx\\peasant\\psyessr2.wav",
            "Gamesfx\\peasant\\psyessr3.wav",
            "Gamesfx\\peasant\\psyessr4.wav",
        ],
        (2 | 16, AudioCue::Ready) => &["Gamesfx\\peasant\\psready.wav"],
        (4 | 5 | 40 | 41 | 45 | 55 | 56, AudioCue::Select) => &["Sfx\\Button.wav"],
        (4 | 5, AudioCue::Order) => &["Gamesfx\\misc\\catyessr.wav"],
        (4 | 5, AudioCue::Ready) => &["Gamesfx\\human\\hready.wav"],
        (6 | 50, AudioCue::Select) => &[
            "Gamesfx\\knight\\knwhat1.wav",
            "Gamesfx\\knight\\knwhat2.wav",
            "Gamesfx\\knight\\knwhat3.wav",
            "Gamesfx\\knight\\knwhat4.wav",
        ],
        (6 | 50, AudioCue::Order) => &[
            "Gamesfx\\knight\\knyessr1.wav",
            "Gamesfx\\knight\\knyessr2.wav",
            "Gamesfx\\knight\\knyessr3.wav",
            "Gamesfx\\knight\\knyessr4.wav",
        ],
        (6 | 50, AudioCue::Ready) => &["Gamesfx\\knight\\knready.wav"],
        (7, AudioCue::Select) => &[
            "Gamesfx\\ogre\\ogwhat1.wav",
            "Gamesfx\\ogre\\ogwhat2.wav",
            "Gamesfx\\ogre\\ogwhat3.wav",
            "Gamesfx\\ogre\\ogwhat4.wav",
        ],
        (7, AudioCue::Order) => &[
            "Gamesfx\\ogre\\ogyessr1.wav",
            "Gamesfx\\ogre\\ogyessr2.wav",
            "Gamesfx\\ogre\\ogyessr3.wav",
        ],
        (7, AudioCue::Ready) => &["Gamesfx\\ogre\\ogready.wav"],
        (8 | 18, AudioCue::Select) => &[
            "Gamesfx\\elves\\ewhat1.wav",
            "Gamesfx\\elves\\ewhat2.wav",
            "Gamesfx\\elves\\ewhat3.wav",
            "Gamesfx\\elves\\ewhat4.wav",
        ],
        (8 | 18, AudioCue::Order) => &[
            "Gamesfx\\elves\\eyessir1.wav",
            "Gamesfx\\elves\\eyessir2.wav",
            "Gamesfx\\elves\\eyessir3.wav",
            "Gamesfx\\elves\\eyessir4.wav",
        ],
        (8 | 18, AudioCue::Ready) => &["Gamesfx\\elves\\eready.wav"],
        (9 | 19 | 53, AudioCue::Select) => &[
            "Gamesfx\\troll\\trwhat1.wav",
            "Gamesfx\\troll\\trwhat2.wav",
            "Gamesfx\\troll\\trwhat3.wav",
        ],
        (9 | 19 | 53, AudioCue::Order) => &[
            "Gamesfx\\troll\\tryessr1.wav",
            "Gamesfx\\troll\\tryessr2.wav",
            "Gamesfx\\troll\\tryessr3.wav",
        ],
        (9 | 19 | 53, AudioCue::Ready) => &["Gamesfx\\troll\\trready.wav"],
        (10, AudioCue::Select) => &[
            "Gamesfx\\wizard\\wzwhat1.wav",
            "Gamesfx\\wizard\\wzwhat2.wav",
            "Gamesfx\\wizard\\wzwhat3.wav",
        ],
        (10, AudioCue::Order) => &[
            "Gamesfx\\wizard\\wzyessr1.wav",
            "Gamesfx\\wizard\\wzyessr2.wav",
            "Gamesfx\\wizard\\wzyessr3.wav",
        ],
        (10, AudioCue::Ready) => &["Gamesfx\\wizard\\wzready.wav"],
        (11 | 51, AudioCue::Select) => &[
            "Gamesfx\\deathknt\\dkwhat1.wav",
            "Gamesfx\\deathknt\\dkwhat2.wav",
        ],
        (11 | 51, AudioCue::Order) => &[
            "Gamesfx\\deathknt\\dkyessr1.wav",
            "Gamesfx\\deathknt\\dkyessr2.wav",
            "Gamesfx\\deathknt\\dkyessr3.wav",
        ],
        (11 | 51, AudioCue::Ready) => &["Gamesfx\\deathknt\\dkready.wav"],
        (12 | 52, AudioCue::Select) => &[
            "Gamesfx\\paladin\\pkwhat1.wav",
            "Gamesfx\\paladin\\pkwhat2.wav",
            "Gamesfx\\paladin\\pkwhat3.wav",
            "Gamesfx\\paladin\\pkwhat4.wav",
        ],
        (12 | 52, AudioCue::Order) => &[
            "Gamesfx\\paladin\\pkyessr1.wav",
            "Gamesfx\\paladin\\pkyessr2.wav",
            "Gamesfx\\paladin\\pkyessr3.wav",
            "Gamesfx\\paladin\\pkyessr4.wav",
        ],
        (12 | 52, AudioCue::Ready) => &["Gamesfx\\paladin\\pkready.wav"],
        (13 | 49, AudioCue::Select) => &[
            "Gamesfx\\ogremage\\omwhat1.wav",
            "Gamesfx\\ogremage\\omwhat2.wav",
            "Gamesfx\\ogremage\\omwhat3.wav",
            "Gamesfx\\ogremage\\omwhat4.wav",
        ],
        (13 | 49, AudioCue::Order) => &[
            "Gamesfx\\ogremage\\omyessr1.wav",
            "Gamesfx\\ogremage\\omyessr2.wav",
            "Gamesfx\\ogremage\\omyessr3.wav",
        ],
        (13 | 49, AudioCue::Ready) => &["Gamesfx\\ogremage\\omready.wav"],
        (14, AudioCue::Select) => &["Gamesfx\\dwarf\\dwhat1.wav", "Gamesfx\\dwarf\\dwhat2.wav"],
        (14, AudioCue::Order) => &[
            "Gamesfx\\dwarf\\dwyessr1.wav",
            "Gamesfx\\dwarf\\dwyessr2.wav",
            "Gamesfx\\dwarf\\dwyessr3.wav",
            "Gamesfx\\dwarf\\dwyessr4.wav",
            "Gamesfx\\dwarf\\dwyessr5.wav",
        ],
        (14, AudioCue::Ready) => &["Gamesfx\\dwarf\\dwready.wav"],
        (15, AudioCue::Select) => &[
            "Gamesfx\\goblin\\gowhat1.wav",
            "Gamesfx\\goblin\\gowhat2.wav",
            "Gamesfx\\goblin\\gowhat3.wav",
            "Gamesfx\\goblin\\gowhat4.wav",
        ],
        (15, AudioCue::Order) => &[
            "Gamesfx\\goblin\\goyessr1.wav",
            "Gamesfx\\goblin\\goyessr2.wav",
            "Gamesfx\\goblin\\goyessr3.wav",
            "Gamesfx\\goblin\\goyessr4.wav",
        ],
        (15, AudioCue::Ready) => &["Gamesfx\\goblin\\goready.wav"],
        (20, AudioCue::Select) => &[
            "Gamesfx\\aleria\\alwhat1.wav",
            "Gamesfx\\aleria\\alwhat2.wav",
            "Gamesfx\\aleria\\alwhat3.wav",
        ],
        (20, AudioCue::Order) => &[
            "Gamesfx\\aleria\\alyessr1.wav",
            "Gamesfx\\aleria\\alyessr2.wav",
            "Gamesfx\\aleria\\alyessr3.wav",
        ],
        (20, AudioCue::Ready) => &["Gamesfx\\human\\hready.wav"],
        (21, AudioCue::Select) => &[
            "Gamesfx\\teron\\tewhat1.wav",
            "Gamesfx\\teron\\tewhat2.wav",
            "Gamesfx\\teron\\tewhat3.wav",
        ],
        (21, AudioCue::Order) => &[
            "Gamesfx\\teron\\teyessr1.wav",
            "Gamesfx\\teron\\teyessr2.wav",
            "Gamesfx\\teron\\teyessr3.wav",
        ],
        (21, AudioCue::Ready) => &["Gamesfx\\orc\\oready.wav"],
        (22, AudioCue::Select) => &[
            "Gamesfx\\kurdran\\kuwhat1.wav",
            "Gamesfx\\kurdran\\kuwhat2.wav",
            "Gamesfx\\kurdran\\kuwhat3.wav",
        ],
        (22, AudioCue::Order) => &[
            "Gamesfx\\kurdran\\kuyessr1.wav",
            "Gamesfx\\kurdran\\kuyessr2.wav",
            "Gamesfx\\kurdran\\kuyessr3.wav",
        ],
        (22, AudioCue::Ready) => &["Gamesfx\\human\\hready.wav"],
        (23, AudioCue::Select) => &[
            "Gamesfx\\dentarg\\odwhat1.wav",
            "Gamesfx\\dentarg\\odwhat2.wav",
            "Gamesfx\\dentarg\\odwhat3.wav",
        ],
        (23, AudioCue::Order) => &[
            "Gamesfx\\dentarg\\odyessr1.wav",
            "Gamesfx\\dentarg\\odyessr2.wav",
            "Gamesfx\\dentarg\\odyessr3.wav",
        ],
        (23, AudioCue::Ready) => &["Gamesfx\\orc\\oready.wav"],
        (24, AudioCue::Select) => &[
            "Gamesfx\\khadgar\\khwhat1.wav",
            "Gamesfx\\khadgar\\khwhat2.wav",
            "Gamesfx\\khadgar\\khwhat3.wav",
        ],
        (24, AudioCue::Order) => &[
            "Gamesfx\\khadgar\\khyessr1.wav",
            "Gamesfx\\khadgar\\khyessr2.wav",
            "Gamesfx\\khadgar\\khyessr3.wav",
        ],
        (24, AudioCue::Ready) => &["Gamesfx\\human\\hready.wav"],
        (25, AudioCue::Select) => &[
            "Gamesfx\\grom\\grwhat1.wav",
            "Gamesfx\\grom\\grwhat2.wav",
            "Gamesfx\\grom\\grwhat3.wav",
        ],
        (25, AudioCue::Order) => &[
            "Gamesfx\\grom\\gryessr1.wav",
            "Gamesfx\\grom\\gryessr2.wav",
            "Gamesfx\\grom\\gryessr3.wav",
        ],
        (25, AudioCue::Ready) => &["Gamesfx\\orc\\oready.wav"],
        (26 | 28 | 30 | 32 | 36 | 38, AudioCue::Select) => &[
            "Gamesfx\\ships\\hshpwht1.wav",
            "Gamesfx\\ships\\hshpwht2.wav",
            "Gamesfx\\ships\\hshpwht3.wav",
        ],
        (26 | 28 | 30 | 32 | 36 | 38, AudioCue::Order) => &[
            "Gamesfx\\ships\\hshpyes1.wav",
            "Gamesfx\\ships\\hshpyes2.wav",
            "Gamesfx\\ships\\hshpyes3.wav",
        ],
        (26 | 28 | 30 | 32 | 36 | 38, AudioCue::Ready) => &["Gamesfx\\ships\\hshpredy.wav"],
        (27 | 29 | 31 | 33 | 37 | 39, AudioCue::Select) => &[
            "Gamesfx\\ships\\oshpwht1.wav",
            "Gamesfx\\ships\\oshpwht2.wav",
            "Gamesfx\\ships\\oshpwht3.wav",
        ],
        (27 | 29 | 31 | 33 | 37 | 39, AudioCue::Order) => &[
            "Gamesfx\\ships\\oshpyes1.wav",
            "Gamesfx\\ships\\oshpyes2.wav",
            "Gamesfx\\ships\\oshpyes3.wav",
        ],
        (27 | 29 | 31 | 33 | 37 | 39, AudioCue::Ready) => &["Gamesfx\\ships\\oshpredy.wav"],
        (35, AudioCue::Select) => &[
            "Gamesfx\\deathwng\\dewhat1.wav",
            "Gamesfx\\deathwng\\dewhat2.wav",
            "Gamesfx\\deathwng\\dewhat3.wav",
        ],
        (35, AudioCue::Order) => &[
            "Gamesfx\\deathwng\\deyessr1.wav",
            "Gamesfx\\deathwng\\deyessr2.wav",
            "Gamesfx\\deathwng\\deyessr3.wav",
        ],
        (35, AudioCue::Ready) => &["Gamesfx\\orc\\oready.wav"],
        (40, AudioCue::Order) => &["Gamesfx\\gnome\\gnyessr1.wav"],
        (40, AudioCue::Ready) => &["Gamesfx\\gnome\\gnready.wav"],
        (41, AudioCue::Order) => &["Gamesfx\\zeppelin\\gbyessr1.wav"],
        (41, AudioCue::Ready) => &["Gamesfx\\zeppelin\\gbready.wav"],
        (42, AudioCue::Select) => &["Gamesfx\\griffon\\grwhat.wav"],
        (42, AudioCue::Order) => &[
            "Gamesfx\\griffon\\griffon1.wav",
            "Gamesfx\\griffon\\griffon2.wav",
        ],
        (42, AudioCue::Ready) => &["Gamesfx\\griffon\\griffon1.wav"],
        (43, AudioCue::Select) => &["Gamesfx\\dragon\\drwhat.wav"],
        (43, AudioCue::Order) => &[
            "Gamesfx\\dragon\\dryessr1.wav",
            "Gamesfx\\dragon\\dryessr2.wav",
        ],
        (43, AudioCue::Ready) => &["Gamesfx\\dragon\\drready.wav"],
        (44, AudioCue::Select) => &[
            "Gamesfx\\turalyon\\tuwhat1.wav",
            "Gamesfx\\turalyon\\tuwhat2.wav",
            "Gamesfx\\turalyon\\tuwhat3.wav",
        ],
        (44, AudioCue::Order) => &[
            "Gamesfx\\turalyon\\tuyessr1.wav",
            "Gamesfx\\turalyon\\tuyessr2.wav",
            "Gamesfx\\turalyon\\tuyessr3.wav",
        ],
        (44, AudioCue::Ready) => &["Gamesfx\\human\\hready.wav"],
        (46, AudioCue::Select) => &[
            "Gamesfx\\danath\\dnwhat1.wav",
            "Gamesfx\\danath\\dnwhat2.wav",
            "Gamesfx\\danath\\dnwhat3.wav",
        ],
        (46, AudioCue::Order) => &[
            "Gamesfx\\danath\\dnyessr1.wav",
            "Gamesfx\\danath\\dnyessr2.wav",
            "Gamesfx\\danath\\dnyessr3.wav",
        ],
        (46, AudioCue::Ready) => &["Gamesfx\\human\\hready.wav"],
        (47, AudioCue::Select) => &[
            "Gamesfx\\kargath\\kawhat1.wav",
            "Gamesfx\\kargath\\kawhat2.wav",
            "Gamesfx\\kargath\\kawhat3.wav",
        ],
        (47, AudioCue::Order) => &[
            "Gamesfx\\kargath\\kayessr1.wav",
            "Gamesfx\\kargath\\kayessr2.wav",
            "Gamesfx\\kargath\\kayessr3.wav",
        ],
        (47, AudioCue::Ready) => &["Gamesfx\\orc\\oready.wav"],
        (55, AudioCue::Order) => &["Gamesfx\\misc\\Skeleton Move.wav"],
        (57, AudioCue::Select) => &["Gamesfx\\misc\\sheep.wav"],
        _ => &[],
    };
    names.iter().map(|s| (*s).to_owned()).collect()
}
